### ISSUE TITLE
Add ability to define time period to NOT download browsers

### ISSUE THREAD

**Issue by gauntface** [GoogleChrome/selenium-assistant#49]
It's handy being able to download latest versions of browsers but it's expensive for network and time.

With the majority of tests using the same path for browsers on a system, it would be good to store the last time a browser was downloaded and allow a test to define how long until a browser should be classed as expired.

This would be done based on hours.

    seleniumAssistant.downloadBrowser('firefox', 'stable',  24)

If the browser was updated less then 24 hours ago then download browser simple resolves, if the browser was last download more than 24 hours ago it will be downloaded.

This is more reliable than force download true or false.

@jeffposnick thoughts on this?

**Comment by jeffposnick** [comment]
I am in favor of any steps towards cutting down on browser downloads and reusing what's already there, for a reasonable interval of time.

(I've been curious—are the automated builds on the Travis CI  infrastructure caching/reusing browser binaries?)

One comment is that moving to named parameter via passing in a configuration object might make sense, rather than using positional parameters. So something like:

```
seleniumAssistant.downloadBrowser({browser: 'firefox', releaseChannel: 'stable', cacheLifetimeInHours: 24});
```

`24` as a third positional parameter is pretty ambiguous—I could see folks reading that and thinking that it's an instruction to download Firefox Stable v24, for instance.

**Comment by addyosmani** [comment]
Fwiw, 👍 the idea of moving towards named keys in a configuration object. That's a lot easier to quickly reason when trying to read through what each thing being passed through corresponds to.

**Comment by gauntface** [comment]
Sorry I completely missed these comments.

If anything else needs adding I'll move to a configuration option.
